name: Docker

on:
  push:
    branches: [main,develop]
  release:
    types: [published]

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: ghcr.io/${{github.repository_owner}}/tree-mask
  VERSION: latest

jobs:
  build-and-push:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: |
        docker build --file Dockerfile -t $IMAGE_NAME_LC:$VERSION .

    - name: Push image
      run: |
        docker push $IMAGE_NAME_LC:$VERSION
