name: Docker

on:
  push:
    branches: [main,develop]
  release:
    types: [published]

permissions:
  packages: write
  contents: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/tree-mask
  VERSION: latest

jobs:
  build-and-push:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
    - name: convert image name to lower case
      run: echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: |
        run: docker build . --file Dockerfile --tag $IMAGE_NAME_LC

    - name: Push image
      run: |
        docker tag $IMAGE_NAME_LC $IMAGE_NAME_LC:$VERSION
        docker push $IMAGE_NAME_LC:$VERSION
